### ISSUE TITLE
Bug: raise EOFError after running for 94000 steps

### ISSUE THREAD

**Issue by GeorgeWuzy** [callmeray/ManiSkill-ViTac2024#14]
INFO - Newton iteration did not converge after 5 iterations, P_inf =4.2246 e-04 (tpC_system.py:610)  
INFO - Step =1, time =0.1000 (ipc_system.py:491)  
INFO - Newton iteration did not converge after 5 iterations, p_inf =2.9361-04 (ipc_system.py:610)  
INFO - Step =2, time =0.2000 (ipc_system.py:491)  
INFO - Newton iteration did not converge after 5 iterations, P_inf = 4.8946e-04 (ipc_system.py:610)  
INFO - Step =3, time =0.3000 (ipc_system.py:491) 
Traceback (most recent call last):  
    File "/home/george/桌面/KCL/ManiSkill-ViTac2024/scripts/universal_training_script.py", line 168, in <module>  
        model.learn(  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/td3/td3.py", line 222, in learn  
        return super().learn(  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 312, in learn  
        rollout = self.collect_rollouts (  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 544, in collect_rollouts  
        new_obs, rewards, dones, infos = env.step(actions)  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 197, in step  
        return self.step_wait()  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 132, in step_wait  
        results = [remote.recv() for remote in self.remotes]  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 132, in <listcomp>  
        results = [remote.recv() for remote in self.remotes]  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 255, in recv  
        buf = self._recv_bytes()  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes  
        buf = self._recv(4)  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 388, in _recv  
        raise EOFError  
EOFError 

After training for 94,000 steps, errors always occur. I believe this might be due to remote.recv() outputting logging information: INFO, and too much output of INFO leads to an EOFError.

**Comment by callmeray** [comment]
You could comment out the `ipc_logger` https://github.com/Rabbit-Hu/sapienipc-exp/blob/a6539b4eead53ef6ac537a86664a386efd3b7869/src/sapienipc/ipc_utils/logging_utils.py#L44

**Comment by GeorgeWuzy** [comment]
Thank you very much for your help, but it seems that even after disabling INFO output, the code still raises an EOFError after about 90,000 steps. Therefore, my previous assumption was incorrect, and there must be another bug here.

’‘’
Traceback (most recent call last):  
    File "/home/george/桌面/KCL/ManiSkill-ViTac2024/scripts/universal_training_script.py", line 168, in <module>  
        model.learn(  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/td3/td3.py", line 222, in learn  
        return super().learn(  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 312, in learn  
        rollout = self.collect_rollouts (  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 544, in collect_rollouts  
        new_obs, rewards, dones, infos = env.step(actions)  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 197, in step  
        return self.step_wait()  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 132, in step_wait  
        results = [remote.recv() for remote in self.remotes]  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 132, in <listcomp>  
        results = [remote.recv() for remote in self.remotes]  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 255, in recv  
        buf = self._recv_bytes()  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes  
        buf = self._recv(4)  
    File "/home/george/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 388, in _recv  
        raise EOFError  
EOFError 
‘’‘
