### ISSUE TITLE
No module named 'sapien.render'

### ISSUE THREAD

**Issue by Marsilea149** [callmeray/ManiSkill-ViTac2024#16]
Hi,

I am trying to install and run the example universal_training_script, but I encountered the following error: 

(mani_vitac) bwu@jilo:~/projects/ManiSkill-ViTac2024$ python scripts/universal_training_script.py --cfg configs/parameters/peg_insertion.yaml [--no_render]
Traceback (most recent call last):
  File "/home/bwu/projects/ManiSkill-ViTac2024/scripts/universal_training_script.py", line 27, in <module>
    from arguments import *
  File "/home/bwu/projects/ManiSkill-ViTac2024/scripts/arguments.py", line 9, in <module>
    from envs.long_open_lock import LongOpenLockParams
  File "/home/bwu/projects/ManiSkill-ViTac2024/scripts/../envs/long_open_lock.py", line 10, in <module>
    from sapienipc.ipc_utils.user_utils import ipc_update_render_all
  File "/home/bwu/projects/sapienipc-exp/src/sapienipc/ipc_utils/user_utils.py", line 3, in <module>
    from sapien.render import RenderCudaMeshComponent
ModuleNotFoundError: No module named 'sapien.render'

Could you please help me? 

Thanks!

**Comment by chuanyune** [comment]
When trying to install sapien, you can attempt to install older versions.

**Comment by Marsilea149** [comment]
Hi,

I realized that warp was not properly built. I built it with cpu. So I tried to build it with cuda, but I encountered another error and I cannot understand what is the issue, here is the log:

(mani_vitac) bwu@coloane:~/projects/gelsight_simulators/sapienipc-exp/warp_$ python build_lib.py --cuda_path="/usr/local/cuda-12.4"
Namespace(msvc_path=None, sdk_path=None, cuda_path='/usr/local/cuda-12.4', mode='release', verbose=True, verify_fp=False, fast_math=False, quick=False, build_llvm=False, debug_llvm=False, standalone=True)
Building /home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/bin/warp.so
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/crt.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/crt.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/cuda_util.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/cuda_util.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/mesh.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/mesh.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/hashgrid.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/hashgrid.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/reduce.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/reduce.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/runlength_encode.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/runlength_encode.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/sort.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/sort.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/sparse.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/sparse.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/volume.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/volume.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/marching.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/marching.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12.4/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/cutlass_gemm.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/cutlass_gemm.cpp.o"
build took 7084.03 ms
"/usr/local/cuda-12.4/bin/nvcc" -O3 --compiler-options -fPIC,-fvisibility=hidden -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_90,code=sm_90 -gencode=arch=compute_90,code=compute_90 -t0 --extended-lambda -DNDEBUG -DWP_ENABLE_CUDA=1 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native" -DWP_ENABLE_CUTLASS=1 -I"warp/native/cutlass/include" -I"warp/native/cutlass/tools/util/include" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cu.o" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cu"
gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
compilation terminated.
nvcc fatal   : Failed to preprocess host compiler properties.
build_cuda took 5.03 ms
Warp build error: Command '"/usr/local/cuda-12.4/bin/nvcc" -O3 --compiler-options -fPIC,-fvisibility=hidden -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_90,code=sm_90 -gencode=arch=compute_90,code=compute_90 -t0 --extended-lambda -DNDEBUG -DWP_ENABLE_CUDA=1 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native" -DWP_ENABLE_CUTLASS=1 -I"warp/native/cutlass/include" -I"warp/native/cutlass/tools/util/include" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cu.o" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cu"' returned non-zero exit status 1.

This is my nvidia-driver version:

(mani_vitac) bwu@coloane:~/projects/gelsight_simulators/sapienipc-exp/warp_$ nvidia-smi
Wed Apr 24 16:52:26 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA T1200 Laptop GPU        Off |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0              7W /   40W |       9MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1458      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A      2780      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+

(mani_vitac) bwu@coloane:~/projects/gelsight_simulators/sapienipc-exp/warp_$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0


I tried with both the main branch and the forked branch(87f79dcee9152c67eb19b07c9c70ae961444cc61) of warp repository. In both cases, I have the same error. 

Thank you very much for your help in advance!

**Comment by callmeray** [comment]
It seems that `cc1plus` is missing in your system. You can try `sudo apt-get install g++`.
Reference: https://stackoverflow.com/questions/8878676/compile-error-g-error-trying-to-exec-cc1plus-execvp-no-such-file-or-dir

**Comment by Marsilea149** [comment]
Hi,

Thank you for your quick reply, I tried sudo apt-get install g++. But it is still giving me the same error. 


(mani_vitac) bwu@coloane : ~/projects/gelsight_simulators/sapienipc-exp/warp_$ sudo apt-get install g++
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:9.3.0-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 214 not upgraded.


(mani_vitac) bwu@coloane:~/projects/gelsight_simulators/sapienipc-exp/warp_$ python build_lib.py --cuda_path="/usr/local/cuda-12"
Namespace(msvc_path=None, sdk_path=None, cuda_path='/usr/local/cuda-12', mode='release', verbose=True, verify_fp=False, fast_math=False, quick=False, build_llvm=False, debug_llvm=False, standalone=True)
Building /home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/bin/warp.so
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/crt.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/crt.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/cuda_util.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/cuda_util.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/mesh.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/mesh.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/hashgrid.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/hashgrid.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/reduce.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/reduce.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/runlength_encode.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/runlength_encode.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/sort.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/sort.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/sparse.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/sparse.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/volume.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/volume.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/marching.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/marching.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=1 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=1 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native"  -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/external/llvm-project/out/install/release-x86_64/include" -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/_build/host-deps/llvm-project/release-x86_64/include" -I"/usr/local/cuda-12/include" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/cutlass_gemm.cpp" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/cutlass_gemm.cpp.o"
build took 7480.76 ms
"/usr/local/cuda-12/bin/nvcc" -O3 --compiler-options -fPIC,-fvisibility=hidden -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_90,code=sm_90 -gencode=arch=compute_90,code=compute_90 -t0 --extended-lambda -DNDEBUG -DWP_ENABLE_CUDA=1 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native" -DWP_ENABLE_CUTLASS=1 -I"warp/native/cutlass/include" -I"warp/native/cutlass/tools/util/include" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cu.o" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cu"
gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
compilation terminated.
nvcc fatal   : Failed to preprocess host compiler properties.
build_cuda took 5.22 ms
Warp build error: Command '"/usr/local/cuda-12/bin/nvcc" -O3 --compiler-options -fPIC,-fvisibility=hidden -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_90,code=sm_90 -gencode=arch=compute_90,code=compute_90 -t0 --extended-lambda -DNDEBUG -DWP_ENABLE_CUDA=1 -I"/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native" -DWP_ENABLE_CUTLASS=1 -I"warp/native/cutlass/include" -I"warp/native/cutlass/tools/util/include" -o "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cu.o" -c "/home/bwu/projects/gelsight_simulators/sapienipc-exp/warp_/warp/native/warp.cu"' returned non-zero exit status 1.
