### ISSUE TITLE
RuntimeError: Failed to load the shared library '/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/bin/warp.so'

### ISSUE THREAD

**Issue by XiaohangShi2000** [callmeray/ManiSkill-ViTac2024#3]
Excuse me, when I try to run the example_peg.py, the following error occurred:
```bash
Traceback (most recent call last):
  File "/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/context.py", line 2494, in load_dll
    dll = ctypes.CDLL(dll_path, winmode=0)
  File "/home/xiaohang_shi/miniconda3/envs/mani_vitac/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xiaohang_shi/miniconda3/envs/mani_vitac/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/bin/warp.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiaohang_shi/Project/ManiSkill-ViTac2024/scripts/universal_training_script.py", line 27, in <module>
    from arguments import *
  File "/home/xiaohang_shi/Project/ManiSkill-ViTac2024/scripts/arguments.py", line 9, in <module>
    from envs.long_open_lock import LongOpenLockParams
  File "/home/xiaohang_shi/Project/ManiSkill-ViTac2024/scripts/../envs/long_open_lock.py", line 35, in <module>
    wp.init()
  File "/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/context.py", line 4102, in init
    runtime = Runtime()
  File "/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/context.py", line 1907, in __init__
    self.core = self.load_dll(warp_lib)
  File "/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/context.py", line 2498, in load_dll
    raise RuntimeError(f"Failed to load the shared library '{dll_path}'")
RuntimeError: Failed to load the shared library '/home/xiaohang_shi/Project/sapienipc-exp/warp_/warp/bin/warp.so'
```
It seems to be that in my virtual environment's libstdc++.so.6, the 'GLIBCXX_3.4.30' is missing.
Could you please tell me how to fix it? Thanks!

**Comment by chuanyune** [comment]
You can try installing the latest version of gcc,
conda install -c conda-forge gcc=12.1.0

**Comment by XiaohangShi2000** [comment]
> You can try installing the latest version of gcc, conda install -c conda-forge gcc=12.1.0

When I run this command, the following error occurrs: 
```bash
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
 - nvidia
 - pytorch
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package _openmp_mutex-5.1-1_gnu requires _libgcc_mutex 0.1 main, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
?? _openmp_mutex 5.1.*  is installable and it requires
?  ?? _libgcc_mutex 0.1 main, which can be installed;
?? gcc 12.1.0**  is not installable because it requires
   ?? gcc_impl_linux-64 12.1.0.* , which requires
      ?? libgomp >=12.1.0 , which requires
         ?? _libgcc_mutex 0.1 conda_forge, which conflicts with any installable versions previously reported.
```
Should I change the channel or uninstall the old gcc version? @cyliizyz

**Comment by chuanyune** [comment]
You can just eh try and run apt-get install libstdc++6 to install the required dependencies.
If that doesn't work, you can run sudo apt-get install gcc-12.1 g++-12.1 to install the new version of gcc.

**Comment by XiaohangShi2000** [comment]
Updating gcc doesn't work. I make a new soft link from /usr/lib/x86_64-linux-gnu/libstdc++.6.0.30 to ~/miniconda/envs/mani_vitac/lib/libstdc++.so.6, then the routine `python scripts/universal_training_script.py --cfg configs/parameters/peg_insertion.yaml` can run normally and no error is reported temporarily.

**Comment by vedantdave97** [comment]
Thanks @XiaohangShi2000 
I had the same issues and this worked. However, I had to overwrite it
```
sudo ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.6.0.30 ~/anaconda3/envs/mani_vitac/lib/libstdc++.so.6
```
