### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by vedantdave97** [callmeray/ManiSkill-ViTac2024#5]
In peg insertion, I am encountering problems when I set `render_rgb=True` in https://github.com/callmeray/ManiSkill-ViTac2024/blob/b77c0da3f1f0a45afc4444fa4b998a539035aeeb/envs/peg_insertion.py#L726

```
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 45, in _worker
    observation, reset_info = env.reset(seed=data)
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/gymnasium/wrappers/env_checker.py", line 57, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py", line 198, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py", line 151, in check_obs
    assert (
AssertionError: The obs returned by the `reset()` method observation keys is not same as the observation space keys, obs keys: ['gt_offset', 'marker_flow', 'rgb_images'], space keys: ['gt_offset', 'marker_flow']
INFO - Newton iteration did not converge after 5 iterations, p_inf = 3.3832e-03 (ipc_system.py:610)
INFO - Entity "tactile_sensor_1" has IPC component but no render component (user_utils.py:72)
INFO - Entity "tactile_sensor_2" has IPC component but no render component (user_utils.py:72)
Traceback (most recent call last):
  File "/home/vedant/ManiSkill-ViTac2024/scripts/universal_training_script.py", line 166, in <module>
    model.learn(
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/td3/td3.py", line 222, in learn
    return super().learn(
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 301, in learn
    total_timesteps, callback = self._setup_learn(
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 284, in _setup_learn
    return super()._setup_learn(
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 424, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 138, in reset
    results = [remote.recv() for remote in self.remotes]
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 138, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/vedant/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
```

In long_open_lock, I do not get the error but I get this:
```
INFO - Entity "tactile_sensor_1" has IPC component but no render component (user_utils.py:72)
INFO - Entity "tactile_sensor_2" has IPC component but no render component (user_utils.py:72)
```
If it is supposed to be like this or if I am doing something wrong, please let me know.

**Comment by callmeray** [comment]
Thank yor for your question. We have fixed the bug in `peg_insetion`. 
The info in `long_open_lock` is not an error. We hide the sensor when rendering, such that we can generate the depth of the sensor surface.
