### ISSUE TITLE
RuntimeError: failed to find a rendering device

### ISSUE THREAD

**Issue by DrWiki** [callmeray/ManiSkill-ViTac2024#6]
when i ran python scripts/universal_training_script.py --cfg configs/parameters/peg_insertion.yaml, there are some errors. 
The first:

   CUDA Toolkit: 11.8, Driver: 12.0
   Devices:
     "cpu"    | x86_64
     "cuda:0" | NVIDIA RTX A6000 (sm_86)
     "cuda:1" | NVIDIA RTX A6000 (sm_86)
     "cuda:2" | NVIDIA RTX A6000 (sm_86)
     "cuda:3" | NVIDIA RTX A6000 (sm_86)
   Kernel cache: /home/ziwu/.cache/warp/1.0.0-beta.2
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/ziwu/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ziwu/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ziwu/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/ziwu/ManiSkill-ViTac2024/scripts/universal_training_script.py", line 39, in _init
    env = gym.make(env_name, **env_args)
  File "/home/ziwu/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/ziwu/ManiSkill-ViTac2024/scripts/../envs/peg_insertion.py", line 750, in __init__
    super(ContinuousInsertionSimGymRandomizedPointFLowEnv, self).__init__(**kwargs)
  File "/home/ziwu/ManiSkill-ViTac2024/scripts/../envs/peg_insertion.py", line 132, in __init__
    self.scene = sapien.Scene()
  File "/home/ziwu/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/sapien/wrapper/scene.py", line 24, in __init__
    [sapien.physx.PhysxCpuSystem(), sapien.render.RenderSystem()]
RuntimeError: failed to find a rendering device

**About this error, i wonder whether the execution of these scripts needs the support of a screen. or special display devices?**  

The other:
Traceback (most recent call last):
  File "/home/ziwu/ManiSkill-ViTac2024/scripts/universal_training_script.py", line 91, in <module>
    env = SubprocVecEnv(
  File "/home/ziwu/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 120, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/home/ziwu/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/ziwu/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/ziwu/anaconda3/envs/mani_vitac/lib/python3.10/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**It looks like i need to connect some hardware to execute that script?**

**Comment by callmeray** [comment]
Thank you for your question. We have added `--no_render` option for training on servers in the lastest commit.

**Comment by Rancho-zhao** [comment]
Hi, I also met a similar issue, and I have set `no_render` to true. The output is as following:

Warp 1.0.0-beta.2 initialized:
   CUDA Toolkit: 11.8, Driver: 12.1
   Devices:
     "cpu"    | x86_64
     "cuda:0" | NVIDIA GeForce RTX 3050 Ti Laptop GPU (sm_86)
   Kernel cache: /home/ViTac2024/sapienipc-exp/build
other arg: cfg is set to configs/parameters/peg_insertion.yaml
other arg: no_render is set to True
Warp 1.0.0-beta.2 initialized:
   CUDA Toolkit: 11.8, Driver: 12.1
   Devices:
     "cpu"    | x86_64
     "cuda:0" | NVIDIA GeForce RTX 3050 Ti Laptop GPU (sm_86)
   Kernel cache: /home/ViTac2024/sapienipc-exp/build
Warp 1.0.0-beta.2 initialized:
   CUDA Toolkit: 11.8, Driver: 12.1
   Devices:
     "cpu"    | x86_64
     "cuda:0" | NVIDIA GeForce RTX 3050 Ti Laptop GPU (sm_86)
   Kernel cache: /home/ViTac2024/sapienipc-exp/build
Process ForkServerProcess-1:
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/ViTac2024/ManiSkill-ViTac2024/scripts/universal_training_script.py", line 42, in _init
    env = gym.make(env_name, device=wp_device, **env_args)
Traceback (most recent call last):
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/ViTac2024/ManiSkill-ViTac2024/scripts/../envs/peg_insertion.py", line 764, in __init__
    super(ContinuousInsertionSimGymRandomizedPointFLowEnv, self).__init__(**kwargs)
  File "/home/ViTac2024/ManiSkill-ViTac2024/scripts/../envs/peg_insertion.py", line 136, in __init__
    self.scene = sapien.Scene()
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/sapien/wrapper/scene.py", line 24, in __init__
    [sapien.physx.PhysxCpuSystem(), sapien.render.RenderSystem()]
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
RuntimeError: failed to find a rendering device
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/ViTac2024/ManiSkill-ViTac2024/scripts/universal_training_script.py", line 42, in _init
    env = gym.make(env_name, device=wp_device, **env_args)
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/ViTac2024/ManiSkill-ViTac2024/scripts/../envs/peg_insertion.py", line 764, in __init__
    super(ContinuousInsertionSimGymRandomizedPointFLowEnv, self).__init__(**kwargs)
  File "/home/ViTac2024/ManiSkill-ViTac2024/scripts/../envs/peg_insertion.py", line 136, in __init__
    self.scene = sapien.Scene()
  File "/root/miniconda3/envs/mani_vitac/lib/python3.10/site-packages/sapien/wrapper/scene.py", line 24, in __init__
    [sapien.physx.PhysxCpuSystem(), sapien.render.RenderSystem()]
RuntimeError: failed to find a rendering device

**Comment by callmeray** [comment]
we just fixed the error. Please try again
